### ISSUE TITLE
Should "virtual organization" be defined?

### ISSUE THREAD

**Issue by dhwalker** [voperson/voperson#12]
There may be two forms of such a definition, the colloquial one:

- An organization that isn't "real" in the usual sense.  It is populated by people from "real" organizations.

and a more IAM-specific one:

- An organization ("real" or otherwise) that includes members whose identity information is obtained from multiple sources (internal and external).

This second definition raises the concept that nearly all organizations (at least in R&E) are VOs (something I've believed for some time).

**Comment by boshrin** [comment]
I'm inclined to go with the second approach. To wordsmith a bit: 

An organization that includes members whose identity information is potentially obtained from multiple sources (internal and external to the organization). The organization may be a physical entity such as a University, or it may be a "virtual" entity, consisting of participants from multiple physical entities. The organization may or may not be a legal entity.

**Comment by dhwalker** [comment]
I like the second approach better, too.  After reading this thread over again, I have some thoughts:  1) Would we consider an organization with multiple sources, all internal, to be virtual?  Probably not.  2) The concept of "physical entity" is, perhaps, confusing.  I'd be tempted to drop it until it's needed elsewhere.

With that in mind, how about, "An organization that includes members whose identity information is obtained from multiple sources, at least one of which is external to the organization. The organization may or may not be a legal entity."?

**Comment by jbasney** [comment]
I like @dhwalker latest proposal.
