### ISSUE TITLE
voPersonAffiliation

### ISSUE THREAD

**Issue by boshrin** [voperson/voperson#22]
eduPersonAffiliation is constrained to 8 defined values. voPersonAffiliation would allow an expanded, vo-specific set of options. (Does this also imply voPersonPrimaryAffiliation and voPersonScopedAffiliation?)

**Comment by dlgroep** [comment]
Isn't the idea close to what "voPersonExternalID" is for identifiers?
So the context of voPerson - in terms of attribute name - the most appropriate would probably be
  "voPersonExternalAffiliation"
- the scoping is implicit just like it is already for the definition of voPEID... and it would match it (hopefully) in scope so you can link the identifier to the affiliation.

**Comment by boshrin** [comment]
The idea behind voPersonAffiliation is that a number of VOs (and institutions) want more affiliations than the standard eduPerson 8. eg: Not just "student" but "gradstudent" and "undergrad". So these are "internal", not "external", and therefore not scoped (or more accurately, implicitly scoped to the VO).

As soon as we do that, it probably makes sense to allow for expanded external scoped affiliations as well. The problem there is these won't be pre-defined, so their use will probably be limited to point-to-point or sub-federation agreements. (ie: If I create instrument-maintenance@myvo.org, does yourvo.org know what that means?)

**Comment by NicolasLiampotis** [comment]
If the voPersonExternalID can also be used for an identifier assigned by a partner institution or VO (i.e. it is not limited to identifiers asserted by home IdPs), why do we need different types of voPersonExternalAffiliation? Is it because of the different affiliation values (standard eduPersonAffiliation vs extended voPersonAffiliation controlled vocabulary)?

**Comment by boshrin** [comment]
@NicolasLiampotis I think the idea is to keep user identifiers separate from what are basically role assertions.

Based on conversations at TNC18, the proposal is now

- voPersonAffiliation as originally proposed, with implicit scope to the local VO when used for local storage and local consumption. This attribute is not intended to be directly reasserted outside the VO. examples: gradstudent, spokesperson
- voPersonExternalAffiliation is a scoped affiliation, which can be used for both storage and transport. Examples: gradstudent@yourvo.org, protocol-researcher@university.edu
- voPersonScopedAffiliation is used for transport only, and maps voPersonAffiliation when used across the wire. The resulting value should be stored in voPersonExternalAffiliation by the receiving entity. Examples: gradstudent@myvo.org, spokesperson@myvo.org
