### ISSUE TITLE
voPerson attribute for per-app password hashes

### ISSUE THREAD

**Issue by jbasney** [voperson/voperson#27]
https://spaces.at.internet2.edu/display/COmanage/Password+Authenticator+Plugin gives us the ability to manage the userPassword attribute but we also have use cases for different app-specific passwords (like https://support.apple.com/en-us/HT204397).

How about a voPersonApplicationPassword attribute (that matches voPersonApplicationUID)?

**Comment by boshrin** [comment]
It's easy enough to define an attribute, but I think the challenge here is on the runtime authentication side. What's using this and how are they verifying the password? I suspect few off the shelf products whether commercial or OSS will support a custom password attribute out of the box, and using LDAP bind for authentication is similarly unlikely to work.

The other option would be to use `userPassword` with attribute options, but that's probably a bad idea as unaware apps could successfully authenticate using the wrong password.

**Comment by boshrin** [comment]
Additional comments from another potential party of interest:

- Include documentation on hash types, potentially including the use of hash types that are not explicitly defined in the spec (if applicable).
- Include guidance for setting up ACLs similar to what [OpenLDAP](https://www.openldap.org/doc/admin24/access-control.html) use/recommends with userPassword by default.

**Comment by boshrin** [comment]
Hey @jbasney, I don't remember if there's a reason this issue is still open. Could you confirm if your original proposal is accomplished?

**Comment by jbasney** [comment]
Confirmed. Thanks!
