### ISSUE TITLE
attribute for agreement to acceptable use policy

### ISSUE THREAD

**Issue by jbasney** [voperson/voperson#3]
Inspired by Peter Gietz's [DARIAH presentation at FIM4R](https://indico.cern.ch/event/647693/#8-dariah):

Do we need an attribute for tracking a user's acceptance of the VO's acceptable use policy? In my experience this is a common requirement for many VOs, and I'm not aware of an existing good LDAP attribute for tracking it.

**Comment by boshrin** [comment]
My proposal would be an attribute with a URL as a value, where the URL describes a pointer to the T&C that were agreed to. We could add agreement time as an attribute option, but that complicates things... is it needed?

eg: `voPersonPolicyAgreement: https://myvo.org/policies/acceptable-use`

vs: `voPersonPolicyAgreement;time-1516593822: https://myvo.org/policies/acceptable-use`

**Comment by jbasney** [comment]
Yes, recording the agreement time is very helpful to know which version of the AUP the user agreed to and whether they need to be prompted to agree to a revised version.
