### ISSUE TITLE
Scope requirement for voPersonExternalID should be relaxed

### ISSUE THREAD

**Issue by skoranda** [voperson/voperson#31]
We want to relax the requirement that voPersonExternalID is an explicitly scoped
identifier since it is helpful to be able to consume and store values
issued by an external authentication service such as a federated or
social identity provider, but which are not explicitly scoped. 

An example would be an eduPersonTargetedID value. While it may have a component
that indicates which SP is targeted and which IdP sent the value, it is not explicitly
"scoped" since the word scope has a specific meaning.

Still, it would be useful to store a value for eduPersonTargetedID into voPersonExternalID.

See PR 30 for suggested change.

https://github.com/voperson/voperson/pull/30

**Comment by boshrin** [comment]
Example added
