### ISSUE TITLE
addition of SSH ldap public key schema

### ISSUE THREAD

**Issue by alanbuxey** [voperson/voperson#37]
requests have come in to deal with SSH public keys being utilised.... presentation
of sshPublicKey value stored in LDAP.  Can this be added to the voPerson? 
the current userCertificate in eduPerson has several issues - eg purpose of key (S/MiME expected etc) and relation with DN

**Comment by boshrin** [comment]
Technically #38 duplicates this, but there's a lot more detail in that issue so I'm going to close this one instead.
